#! /usr/bin/env bash
#SBATCH -A ops
#SBATCH -t {{ time }}
#SBATCH -N {{ nodes }}
#SBATCH -n {{ procs }}
#SBATCH -p phi
#SBATCH -o outputs/slurm.{{ hash }}.out
#SBATCH -e outputs/slurm.{{ hash }}.err

run_id="{{ hash }}"
method="{{ method }}"
data_per_node="{{ data }}"
num_procs={{ procs }}
num_nodes={{ nodes }}
num_loops_sn="5 * (10 ^ 5)"
# num_loops_sn="10"
num_loops=$( echo "$num_loops_sn" | bc)
mpi_version="{{ mpi }}"

set -x
module purge
module load gcc/7.3.0
module load $mpi_version
which mpirun
which mpicc
make opt
chmod +x treegather.bin
ldd treegather.bin

touch 'time/start.{{ hash }}.time'
mpirun -n $num_procs $(pwd)/treegather.bin \
    --gather-method $method \
    --num-loops $num_loops \
    --data-per-node $(echo $data_per_node | bc)
touch 'time/end.{{ hash }}.time'

echo
time=$(ls --full-time 'time/start.{{ hash }}.time' 'time/end.{{ hash }}.time' \
    | cut -f7 -d' ' \
    | tr '\n' ';' \
    | sed 's/;//2')
printf "{\"mpi\": \"$mpi_version\", \"data_per_proc\": \"$data_per_node\", \"method\": \"$method\", \"num_procs\": \"$num_procs\", \"num_nodes\": \"$num_nodes\", \"num_loops\": \"$num_loops_sn\", \"time\": \"$time\"}\n"
